### ISSUE TITLE
Option for "breakerofchains_view_result"?

### ISSUE THREAD

**Issue by chorgan182** [MilesMcBain/breakerofchains#15]
Firstly, thank you for the package! I am finding it quite useful. 

In the context of `dplyr` chains, I found myself immediately using `View(.chain)` after calling the addin. Usually, I will want to view the whole dataframe for the intermediate results of some actions. My quick hack for this was adding a `View()` right after the assignment of `.chain`, as follows:

```
    if (getOption("breakerofchains_store_result", TRUE)) {
      assign(".chain", .chain, .GlobalEnv)
      View(.chain)
    }
```

Do you think it would be worth it to add another option, similar to "breakerofchains_store_result", that would allow viewing to happen automatically? Default could be FALSE. I'd be happy to implement if you agree.

**Comment by MilesMcBain** [comment]
Thanks for raising this @chorgan182!

You opened my eyes to a limitation of this tool. It wasn't very extensible for users. You had to change the source to get that behaviour and that's not great. Rather than go with your proposed solution I decided to better facilitate users to build on top of what's here, and so present the result of chain evaluation however they want.

This made sense to me because while it's `View()` for you, it could just as easily be `glimpse()` or `paint()` or whatever for someone else.

I put a little example in the `NEWS.md` of how to rig up the behaviour you want using `shrtcts`. Let me know if you have trouble figuring it out, and I can elaborate.

**Comment by chorgan182** [comment]
This is *much* better solution than mine. I just got it working smoothly. Thank you for the quick update!
